### PR TITLE
fix #54

### LINKED ISSUE #54: Add support for NixOS
It would be very cool to have support for NixOS :)

### PR DESCRIPTION
**Pull request by HannesGitH**
Unfortunately Im stuck as i cannot get the core_lib dependency into yarn2nix

### CODE REVIEW

**Comment by Martichou** [comment]
Hi, thanks! 

I'm not sure if I can help, can you explain a bit more about the issue and what you're trying to achieve with the yarn2nix? (I'm very not familiar with any of that)

**Comment by HannesGitH** [comment]
> Hi, thanks!
> 
> I'm not sure if I can help, can you explain a bit more about the issue and what you're trying to achieve with the yarn2nix? (I'm very not familiar with any of that)

Sure thing :)

I've added a bit more detail in the linked issue over at nixpkgs, since I think they might have a better clue.

but the TLDR is that i cannot find the 'nix-way' of adding the local `../core_lib` as a dependency of the frontend.

Why the 'nix-way' ? nix has very different goals than other distros, as i tries to get everything deterministic. This results in packages being able to be built from source either without network or with hashes known in advance.
And as `pnpm install` fetches stuff from the internet and adds timestamps etc, this cannot really be used in a deterministic build process. However nix provides yarn2nix which can prefetch node dependencies provided in a yarn.lock deterministically. Unfortunately though, this convenience function (yarn2nix, or by extend mkYarnPackage) doesnt really operate well with local dependencies, or at least I dont know how. Thats where I need help from the yarn2nix team.

**Comment by Martichou** [comment]
Ok, thanks for the explanation! As expected I can't help with that but that's very nice of you to handle it ;)

**Comment by HannesGitH** [comment]
closed in favor of simply wrapping the appImage in nixpkgs:
https://github.com/NixOS/nixpkgs/pull/311593

**Pull request closed without merging**
