### PR TITLE
feat: support macos

### PR DESCRIPTION
**Pull request by JurianOnderwater**
I broke everything in my main branch, I'll close that pull request and replace it with this one. It's ready for review I guess.

### CODE REVIEW

**Comment by JurianOnderwater** [comment]
I put some #[cfg(not(target_os = "macos"))] in notification.rs cause the n.wait_for_action was throwing errors, and the notifications don't work for macos anyway

**Comment by Martichou** [comment]
Thanks! I'll wait to have access to a Mac before merging this.
I'll try to fix the notification and the sending :)

**Comment by Martichou** [comment]
I'll try to get my hands on one this Friday!

**Comment by polnico** [comment]
Hey @pythongod , I was able to make this work on my machine and also fix the notiifcation issue on MacOS (at least on my machine). Would you be ok to open this PR (or you fork) so that I can edit it and add the notification fix to your commit ? I can also just send you a patchset if easier for you.

**Comment by Martichou** [comment]
@polnico you'll need to open a new PR which can be based on this one, that's no issue, you just can't modify this PR :)

**Comment by Martichou** [comment]
Closing in favor of #114 (I modified it but still gave you credits for the commit)

**Pull request closed without merging**
